---
title: "Final ML Runs"
output: html_notebook
---

This notebook runs the complete hurdle models for RFMO dataset.

```{r message=FALSE, warning=FALSE, include=FALSE}
# General
library(raster)
library(sf)
library(fasterize)
library(scales)
library(knitr)
library(RColorBrewer)
library(readxl)
library(googledrive)
library(cowplot)
library(tidyverse)
library(sp)
library(rgdal)
library(geosphere)
library(paletteer)

# Neg Binomial Libraries
library(pscl)

# ML Libraries
library(tidymodels)
library(readr)
library(broom.mixed)
library(MultivariateRandomForest)
library(vroom)

options(scipen = 1000000)

# Get functions
source(file.path(here::here(), "src/functions/func-all_rfmo_effort_models.R"))
source(file.path(here::here(), "src/functions/func-all_rfmo_other_models.R"))
source(file.path(here::here(), "src/functions/func-all_rfmo_untuned_models.R"))
source(file.path(here::here(), "src/functions/func-train_test_split.R"))
source(file.path(here::here(), "src/functions/func-all_rfmo_untuned_models_quantile.R"))

save_loc <- file.path(here::here(), "data-updated/model-data/outputs/all-rfmo-models/")
```

```{r include=FALSE}
# Read in data... 
# 5x5 data - count only
list_files<- list.files(file.path(here::here(), "data-updated/model-data/inputs/all-rfmo-models/"), pattern = "5x5_count_hooks.csv", full.names = T)

count_5x5_obs <- NULL 

for(file in list_files) {
  temp <- read.csv(file)
  count_5x5_obs <- bind_rows(count_5x5_obs, temp)
} 

list_files<- list.files(file.path(here::here(), "data-updated/model-data/inputs/all-rfmo-models/"), pattern = "5x5_count_kwh.csv", full.names = T)

count_5x5_gfw <- NULL

for(file in list_files) {
  temp <- read.csv(file)
  count_5x5_gfw <- bind_rows(count_5x5_gfw, temp)
} 
  
# 5x5 data - mt and count
list_files<- list.files(file.path(here::here(), "data-updated/model-data/inputs/all-rfmo-models/"), pattern = "5x5_mt_to_count_hooks.csv", full.names = T)

mt_5x5_obs <- NULL 

for(file in list_files) {
  temp <- read.csv(file)
  mt_5x5_obs <- bind_rows(mt_5x5_obs, temp)
} 

list_files<- list.files(file.path(here::here(), "data-updated/model-data/inputs/all-rfmo-models/"), pattern = "5x5_mt_to_count_kwh.csv", full.names = T)

mt_5x5_gfw <- NULL

for(file in list_files) {
  temp <- read.csv(file)
  mt_5x5_gfw <- bind_rows(mt_5x5_gfw, temp)
} 

# 1x1 data - count only
list_files<- list.files(file.path(here::here(), "data-updated/model-data/inputs/all-rfmo-models/"), pattern = "1x1_count_hooks.csv", full.names = T)

count_1x1_obs <- NULL 

for(file in list_files) {
  temp <- read.csv(file)
  count_1x1_obs <- bind_rows(count_1x1_obs, temp)
} 

list_files<- list.files(file.path(here::here(), "data-updated/model-data/inputs/all-rfmo-models/"), pattern = "1x1_count_kwh.csv", full.names = T)

count_1x1_gfw <- NULL

for(file in list_files) {
  temp <- read.csv(file)
  count_1x1_gfw <- bind_rows(count_1x1_gfw, temp)
} 
  
# 1x1 data - mt and count
list_files<- list.files(file.path(here::here(), "data-updated/model-data/inputs/all-rfmo-models/"), pattern = "1x1_mt_to_count_hooks.csv", full.names = T)

mt_1x1_obs <- NULL 

for(file in list_files) {
  temp <- read.csv(file)
  mt_1x1_obs <- bind_rows(mt_1x1_obs, temp)
} 

list_files<- list.files(file.path(here::here(), "data-updated/model-data/inputs/all-rfmo-models/"), pattern = "1x1_mt_to_count_kwh.csv", full.names = T)

mt_1x1_gfw <- NULL

for(file in list_files) {
  temp <- read.csv(file)
  mt_1x1_gfw <- bind_rows(mt_1x1_gfw, temp)
} 
```

```{r eval=FALSE, include=FALSE}
# Run effort scenarios... 
# 5x5 data - count only
results_5x5_count <- all_rfmo_effort_models(data_gfw = count_5x5_gfw, data_effort = count_5x5_obs, save_loc = paste0(save_loc, "5x5_count_"))

# 5x5 data - mt and count
results_5x5_mt <- all_rfmo_effort_models(data_gfw = mt_5x5_gfw, data_effort = mt_5x5_obs, save_loc = paste0(save_loc, "5x5_mt_to_count_"))

# 1x1 data - count only
results_1x1_count <- all_rfmo_effort_models(data_gfw = count_1x1_gfw, data_effort = count_1x1_obs, save_loc = paste0(save_loc, "1x1_count_"))

# 1x1 data - mt and count
results_1x1_mt <- all_rfmo_effort_models(data_gfw = mt_1x1_gfw, data_effort = mt_1x1_obs, save_loc = paste0(save_loc, "1x1_mt_to_count_"))
```

```{r}
# Check best performing models in terms of effort
effort_model_results <- read.csv(paste0(save_loc, "5x5_count_all_rfmos_ll_effort_results.csv")) %>%
              mutate(type = "regular", 
                     option = "5x5, count only") %>% 
  bind_rows(read.csv(paste0(save_loc, "5x5_mt_to_count_all_rfmos_ll_effort_results.csv")) %>%
              mutate(type = "regular", 
                     option = "5x5, count and mt")) %>%
  bind_rows(read.csv(paste0(save_loc, "1x1_count_all_rfmos_ll_effort_results.csv")) %>%
              mutate(type = "regular", 
                     option = "1x1, count only")) %>% 
  bind_rows(read.csv(paste0(save_loc, "1x1_mt_to_count_all_rfmos_ll_effort_results.csv")) %>%
              mutate(type = "regular", 
                     option = "1x1, count and mt")) 

effort_model_results_p1 <- effort_model_results %>%
  dplyr::select(rfmo, type, option, effort_source, rsq) %>%
  group_by(rfmo) %>% 
  slice_max(., n = 1, rsq) %>% 
  mutate(df_name = paste0(ifelse(grepl("mt", option), "mt_", "count_"), 
                          ifelse(grepl("1x1", option), "1x1_", "5x5_"), 
                          ifelse(grepl("target|bycatch", effort_source), "obs", "gfw")))

effort_model_results_p1
```


```{r}
# Best performing models in terms of effort
for(selected_rfmo in c("IATTC", "ICCAT", "IOTC", "WCPFC")) { 

all_rfmo_other_models(data = eval(as.name(effort_model_results_p1$df_name[which(effort_model_results_p1$rfmo == selected_rfmo)])), 
                      rfmos = selected_rfmo, 
                      effort_source = effort_model_results_p1$effort_source[which(effort_model_results_p1$rfmo == selected_rfmo)], 
                      save_loc = save_loc)

} 
```

```{r}
# Find best performing models
all_model_results <- effort_model_results %>% 
  bind_rows(read.csv(paste0(save_loc, "IATTC_ll_models_others_results.csv")) %>%
              mutate(type = "exhaustive search", 
                     rfmo = "IATTC",
                     option = effort_model_results_p1$option[which(effort_model_results_p1$rfmo == "IATTC")], 
                     effort_source = effort_model_results_p1$effort_source[which(effort_model_results_p1$rfmo == "IATTC")]) %>% 
              rowwise() %>% 
              mutate(specifics = paste0("environmentals = ", environmental_value, ", include ssh = ", 
                                        include_ssh, ", price = ", price, ", catch transformation = ", catch_transformation), 
                     option = paste0(option, ";", specifics))) %>% 
  bind_rows(read.csv(paste0(save_loc, "ICCAT_ll_models_others_results.csv")) %>%
              mutate(type = "exhaustive search", 
                     rfmo = "ICCAT",
                     option = effort_model_results_p1$option[which(effort_model_results_p1$rfmo == "ICCAT")], 
                     effort_source = effort_model_results_p1$effort_source[which(effort_model_results_p1$rfmo == "ICCAT")]) %>% 
              rowwise() %>% 
              mutate(specifics = paste0("environmentals = ", environmental_value, ", include ssh = ", 
                                        include_ssh, ", price = ", price, ", catch transformation = ", catch_transformation), 
                     option = paste0(option, ";", specifics))) %>% 
  bind_rows(read.csv(paste0(save_loc, "IOTC_ll_models_others_results.csv")) %>%
              mutate(type = "exhaustive search", 
                     rfmo = "IOTC",
                     option = effort_model_results_p1$option[which(effort_model_results_p1$rfmo == "IOTC")], 
                     effort_source = effort_model_results_p1$effort_source[which(effort_model_results_p1$rfmo == "IOTC")]) %>% 
              rowwise() %>% 
              mutate(specifics = paste0("environmentals = ", environmental_value, ", include ssh = ", 
                                        include_ssh, ", price = ", price, ", catch transformation = ", catch_transformation), 
                     option = paste0(option, ";", specifics))) %>% 
  bind_rows(read.csv(paste0(save_loc, "WCPFC_ll_models_others_results.csv")) %>%
              mutate(type = "exhaustive search", 
                     rfmo = "WCPFC",
                     option = effort_model_results_p1$option[which(effort_model_results_p1$rfmo == "WCPFC")], 
                     effort_source = effort_model_results_p1$effort_source[which(effort_model_results_p1$rfmo == "WCPFC")]) %>% 
              rowwise() %>% 
              mutate(specifics = paste0("environmentals = ", environmental_value, ", include ssh = ", 
                                        include_ssh, ", price = ", price, ", catch transformation = ", catch_transformation), 
                     option = paste0(option, ";", specifics)))

all_model_results_p2 <- all_model_results %>%
  dplyr::select(rfmo, type, option, effort_source, rsq, mtry_class, min_n_class, mtry_reg, min_n_reg) %>%
  group_by(rfmo) %>% 
  slice_max(., n = 1, rsq)

all_model_results_p2
```


```{r warning=FALSE}
# Re-run untuned best performing model

for(selected_rfmo in c("IATTC", "ICCAT", "IOTC", "WCPFC")) { 

  rfmo_model_option <- all_model_results_p2 %>% filter(rfmo == selected_rfmo)
  
  rfmo_data <- eval(as.name(effort_model_results_p1$df_name[which(effort_model_results_p1$rfmo ==
                                                                    selected_rfmo)]))
  
  rfmo_effort_variables <- case_when(selected_rfmo == "WCPFC" & 
                                       grepl("bycatch", rfmo_model_option$effort_source) ~
                                       "bycatch_total_effort$", 
                                     grepl("target", rfmo_model_option$effort_source) ~ 
                                        paste0(colnames(rfmo_data)[grepl("target_effort_",
                                                                         colnames(rfmo_data))],   
                                               collapse = "$|"), 
                                      grepl("bycatch", rfmo_model_option$effort_source) ~ 
                                        paste0(colnames(rfmo_data)[grepl("bycatch_total_effort_",  
                                                                         colnames(rfmo_data))], collapse = "$|"),
                                     grepl("gfw", rfmo_model_option$effort_source) ~
                                        "total_fishing_kwh$")
  
  if(grepl("gfw", rfmo_model_option$effort_source)) { 
    rfmo_data <- rfmo_data %>% 
      mutate(effort_units = "kwh")
  }
  
  rfmo_other_variables <- paste0("species_commonname$|sdm$|mean_sst$|mean_chla$|", 
                                  case_when(grepl("environmentals = mean, include ssh = TRUE",
                                               rfmo_model_option$option) ~ "mean_ssh$|", 
                                            TRUE ~ ""), 
                                  case_when(grepl("environmentals = meancv", rfmo_model_option$option) ~ 
                                              "cv_sst$|cv_chla$|", 
                                            TRUE ~ ""), 
                                  case_when(grepl("environmentals = meancv, include ssh = TRUE",
                                               rfmo_model_option$option) ~ "mean_ssh$|cv_ssh$|", 
                                            TRUE ~ ""), 
                                  case_when(grepl("price = speciesprice", rfmo_model_option$option) ~ 
                                              "median_price_species$|", 
                                            TRUE ~ ""), 
                                  case_when(grepl("price = groupprice", rfmo_model_option$option) ~ 
                                              "median_price_species$|", 
                                            TRUE ~ ""))
  
  # Note - there will be warnings for NAs but this is just from the enviro data that is NA in the original
  # data as well carrying over into the pedicted data
  all_rfmo_untuned_models(data = rfmo_data,
                  rfmos = selected_rfmo,
                  effort_source = rfmo_model_option$effort_source,
                  classification_variables = paste0(rfmo_other_variables, rfmo_effort_variables),
                  regression_variables = paste0(rfmo_other_variables, rfmo_effort_variables),
                  save_loc = save_loc,
                  logtrans = ifelse(grepl("catch transformation = log", rfmo_model_option$option), 
                                    TRUE, FALSE), 
                  mtry_class = rfmo_model_option$mtry_class, 
                  min_n_class = rfmo_model_option$min_n_class, 
                  mtry_reg = rfmo_model_option$mtry_reg, 
                  min_n_reg = rfmo_model_option$min_n_reg)
} 
```


```{r}
# Final check of results
untuned_iattc <- readRDS(paste0(save_loc, "IATTC_ll_untuned_model.rds"))

untuned_iccat <- readRDS(paste0(save_loc, "ICCAT_ll_untuned_model.rds"))

untuned_iotc <- readRDS(paste0(save_loc, "IOTC_ll_untuned_model.rds"))

untuned_wcpfc <- readRDS(paste0(save_loc, "WCPFC_ll_untuned_model.rds"))

bind_rows(untuned_iattc$test_metrics, untuned_iccat$test_metrics, 
                      untuned_iotc$test_metrics, untuned_wcpfc$test_metrics) %>% 
  select(rfmo, rsq) %>% 
  rename(untuned_rsq = rsq) %>%
  left_join(all_model_results_p2 %>% 
              select(rfmo, rsq) %>% 
              rename(original_rsq = rsq))
```

```{r}
# Plot feature importance for each portion of the model
for(rfmo in c("iattc", "iccat", "iotc", "wcpfc")) { 
  temp <- eval(as.name(paste0("untuned_", rfmo)))$feature_importance
  
  feature_importance <- temp %>%
      mutate(Variable = str_to_lower(Variable),
             Variable = gsub("species_commonname_", "(species) ", Variable),
             Variable = gsub("target_effort_", "(target effort) ", Variable), 
             Variable = gsub("bycatch_total_effort_", "(bycatch effort) ", Variable),
             Variable = gsub("_|[.]", " ", Variable))
  
    ggplot(data = feature_importance %>% 
             arrange(desc(Importance)), aes(x = Importance, y = Variable)) +
      geom_point() +
      facet_wrap(vars(component), scales = "free_x") +
      ylab("")
    
    ggsave(file.path(here::here(), "figures/supplemental/", paste0(rfmo, "_featureimportance.png")),
           width = 10, height = 6, units = "in", bg = "white")

  }
```

```{r}
# Run again but calculate quantiles 
save_loc <- file.path(here::here(), "data-updated/model-data/outputs/all-rfmo-models/quantiles/")

# Re-run untuned best performing model

for(selected_rfmo in c("ICCAT", "IOTC", "WCPFC", "IATTC")) { 

  rfmo_model_option <- all_model_results_p2 %>% filter(rfmo == selected_rfmo)
  
  rfmo_data <- eval(as.name(effort_model_results_p1$df_name[which(effort_model_results_p1$rfmo ==
                                                                    selected_rfmo)]))
  
  rfmo_effort_variables <- case_when(selected_rfmo == "WCPFC" & 
                                       grepl("bycatch", rfmo_model_option$effort_source) ~
                                       "bycatch_total_effort$", 
                                     grepl("target", rfmo_model_option$effort_source) ~ 
                                        paste0(colnames(rfmo_data)[grepl("target_effort_",
                                                                         colnames(rfmo_data))],   
                                               collapse = "$|"), 
                                      grepl("bycatch", rfmo_model_option$effort_source) ~ 
                                        paste0(colnames(rfmo_data)[grepl("bycatch_total_effort_",  
                                                                         colnames(rfmo_data))], collapse = "$|"),
                                     grepl("gfw", rfmo_model_option$effort_source) ~
                                        "total_fishing_kwh$")
  
  if(grepl("gfw", rfmo_model_option$effort_source)) { 
    rfmo_data <- rfmo_data %>% 
      mutate(effort_units = "kwh")
  }
  
  rfmo_other_variables <- paste0("species_commonname$|sdm$|mean_sst$|mean_chla$|", 
                                  case_when(grepl("environmentals = mean, include ssh = TRUE",
                                               rfmo_model_option$option) ~ "mean_ssh$|", 
                                            TRUE ~ ""), 
                                  case_when(grepl("environmentals = meancv", rfmo_model_option$option) ~ 
                                              "cv_sst$|cv_chla$|", 
                                            TRUE ~ ""), 
                                  case_when(grepl("environmentals = meancv, include ssh = TRUE",
                                               rfmo_model_option$option) ~ "mean_ssh$|cv_ssh$|", 
                                            TRUE ~ ""), 
                                  case_when(grepl("price = speciesprice", rfmo_model_option$option) ~ 
                                              "median_price_species$|", 
                                            TRUE ~ ""), 
                                  case_when(grepl("price = groupprice", rfmo_model_option$option) ~ 
                                              "median_price_species$|", 
                                            TRUE ~ ""))
  
  # Note - there will be warnings for NAs but this is just from the enviro data that is NA in the original
  # data as well carrying over into the pedicted data
  all_rfmo_untuned_models_quantile(data = rfmo_data,
                  rfmos = selected_rfmo,
                  effort_source = rfmo_model_option$effort_source,
                  classification_variables = paste0(rfmo_other_variables, rfmo_effort_variables),
                  regression_variables = paste0(rfmo_other_variables, rfmo_effort_variables),
                  save_loc = save_loc,
                  logtrans = ifelse(grepl("catch transformation = log", rfmo_model_option$option), 
                                    TRUE, FALSE), 
                  mtry_class = rfmo_model_option$mtry_class, 
                  min_n_class = rfmo_model_option$min_n_class, 
                  mtry_reg = rfmo_model_option$mtry_reg, 
                  min_n_reg = rfmo_model_option$min_n_reg, 
                  original_output = file.path(here::here(), "data-updated/model-data/outputs/all-rfmo-models", paste0(selected_rfmo, "_ll_untuned_model.rds")))
} 
```

```{r}
# Check results 
untuned_iattc <- readRDS(paste0(save_loc, "IATTC_ll_untuned_model.rds"))

untuned_iccat <- readRDS(paste0(save_loc, "ICCAT_ll_untuned_model.rds"))

untuned_iotc <- readRDS(paste0(save_loc, "IOTC_ll_untuned_model.rds"))

untuned_wcpfc <- readRDS(paste0(save_loc, "WCPFC_ll_untuned_model.rds"))
```

```{r}
# Run again, but for all sharks
save_loc <- file.path(here::here(), "data-updated/model-data/outputs/all-rfmo-models/all-sharks-model/")

for(selected_rfmo in c("ICCAT", "IOTC", "WCPFC", "IATTC")) { 

  rfmo_model_option <- all_model_results_p2 %>% filter(rfmo == selected_rfmo)
  
  rfmo_data <- eval(as.name(effort_model_results_p1$df_name[which(effort_model_results_p1$rfmo ==
                                                                    selected_rfmo)])) 
  
  rfmo_data <- rfmo_data %>% 
    mutate_at(colnames(.)[grepl("target_effort|bycatch_total_effort|sst|chla|ssh|sdm|price", colnames(.))], as.numeric) %>% 
    group_by(latitude, longitude, year, rfmo, gear_group, catch_units, effort_units, spatial_notes, species_group) %>% 
    summarise(across(where(is.numeric) & !catch, mean, na.rm = T), 
              catch = sum(catch, na.rm = T)) %>% 
    ungroup() %>% 
    mutate(species_commonname = "SHARKS", 
           species_sciname = "SHARKS", 
           species_resolution = "NEI") %>% 
    select(colnames(rfmo_data))
  
  rfmo_effort_variables <- case_when(selected_rfmo == "WCPFC" & 
                                       grepl("bycatch", rfmo_model_option$effort_source) ~
                                       "bycatch_total_effort$", 
                                     grepl("target", rfmo_model_option$effort_source) ~ 
                                        paste0(colnames(rfmo_data)[grepl("target_effort_",
                                                                         colnames(rfmo_data))],   
                                               collapse = "$|"), 
                                      grepl("bycatch", rfmo_model_option$effort_source) ~ 
                                        paste0(colnames(rfmo_data)[grepl("bycatch_total_effort_",  
                                                                         colnames(rfmo_data))], collapse = "$|"),
                                     grepl("gfw", rfmo_model_option$effort_source) ~
                                        "total_fishing_kwh$")
  
  if(grepl("gfw", rfmo_model_option$effort_source)) { 
    rfmo_data <- rfmo_data %>% 
      mutate(effort_units = "kwh")
  }
  
  rfmo_other_variables <- paste0("species_commonname$|sdm$|mean_sst$|mean_chla$|", 
                                  case_when(grepl("environmentals = mean, include ssh = TRUE",
                                               rfmo_model_option$option) ~ "mean_ssh$|", 
                                            TRUE ~ ""), 
                                  case_when(grepl("environmentals = meancv", rfmo_model_option$option) ~ 
                                              "cv_sst$|cv_chla$|", 
                                            TRUE ~ ""), 
                                  case_when(grepl("environmentals = meancv, include ssh = TRUE",
                                               rfmo_model_option$option) ~ "mean_ssh$|cv_ssh$|", 
                                            TRUE ~ ""), 
                                  case_when(grepl("price = speciesprice", rfmo_model_option$option) ~ 
                                              "median_price_species$|", 
                                            TRUE ~ ""), 
                                  case_when(grepl("price = groupprice", rfmo_model_option$option) ~ 
                                              "median_price_species$|", 
                                            TRUE ~ ""))
  
  # Note - there will be warnings for NAs but this is just from the enviro data that is NA in the original
  # data as well carrying over into the pedicted data
  all_rfmo_untuned_models_quantile(data = rfmo_data,
                  rfmos = selected_rfmo,
                  effort_source = rfmo_model_option$effort_source,
                  classification_variables = paste0(rfmo_other_variables, rfmo_effort_variables),
                  regression_variables = paste0(rfmo_other_variables, rfmo_effort_variables),
                  save_loc = save_loc,
                  logtrans = ifelse(grepl("catch transformation = log", rfmo_model_option$option), 
                                    TRUE, FALSE), 
                  mtry_class = rfmo_model_option$mtry_class, 
                  min_n_class = rfmo_model_option$min_n_class, 
                  mtry_reg = rfmo_model_option$mtry_reg, 
                  min_n_reg = rfmo_model_option$min_n_reg)
} 
```

```{r}
catch_presence <- NULL
for(selected_rfmo in c("ICCAT", "IOTC", "WCPFC", "IATTC")) { 

  rfmo_model_option <- all_model_results_p2 %>% filter(rfmo == selected_rfmo)
  
  rfmo_data <- eval(as.name(effort_model_results_p1$df_name[which(effort_model_results_p1$rfmo ==
                                                                    selected_rfmo)])) 
  if(grepl("gfw", rfmo_model_option$effort_source)) { 
    rfmo_data <- rfmo_data %>% 
      mutate(effort_units = "kwh")
    }
  
  rfmo_data <- rfmo_data %>% 
    mutate_at(colnames(.)[grepl("target_effort|bycatch_total_effort|sst|chla|ssh|sdm|price", colnames(.))], as.numeric) %>% 
    group_by(latitude, longitude, year, rfmo, gear_group, catch_units, effort_units, spatial_notes, species_group) %>% 
    summarise(across(where(is.numeric) & !catch, mean, na.rm = T), 
              catch = sum(catch, na.rm = T)) %>% 
    ungroup() %>% 
    mutate(species_commonname = "SHARKS", 
           species_sciname = "SHARKS", 
           species_resolution = "NEI") %>% 
    select(colnames(rfmo_data)) 
  
  rfmo_data <- rfmo_data %>% 
    filter(rfmo == selected_rfmo) %>% 
    mutate(catch_fact = ifelse(catch >0, 1, 0)) %>% 
    group_by(catch_fact) %>% 
    summarise(n = n()) %>% 
    ungroup() %>% 
    mutate(rfmo = selected_rfmo)
  
  catch_presence <- catch_presence %>% 
    rbind(rfmo_data)
} 
```


