---
title: "Final ML Runs"
output: html_notebook
---

This notebook runs the complete hurdle models for RFMO dataset.

```{r message=FALSE, warning=FALSE, include=FALSE}
# General
library(raster)
library(sf)
library(fasterize)
library(scales)
library(knitr)
library(RColorBrewer)
library(readxl)
library(googledrive)
library(cowplot)
library(tidyverse)
library(sp)
library(rgdal)
library(geosphere)
library(paletteer)

# Neg Binomial Libraries
library(pscl)

# ML Libraries
library(tidymodels)
library(readr)
library(broom.mixed)
library(MultivariateRandomForest)
library(vroom)

options(scipen = 1000000)

# Get functions
source("../functions/func-all_rfmo_models.R")
source("../functions/func-all_rfmo_effort_models.R")
source("../functions/func-all_rfmo_selector_models.R")
source("../functions/func-run_all_rfmo_models_others.R")
source("../functions/func-train_all_models.R")
source("../functions/func-train_test_split.R")

save_loc = "../../data/model-data/outputs/all-rfmo-models/"
```

```{r include=FALSE}
# Read in data... 
# 5x5 data - count only
list_files<- list.files("../../data/model-data/inputs/all-rfmo-models/", pattern = "5x5_count_hooks.csv", full.names = T)

count_5x5_obs <- NULL 

for(file in list_files) {
  temp <- read.csv(file)
  count_5x5_obs <- bind_rows(count_5x5_obs, temp)
} 

list_files<- list.files("../../data/model-data/inputs/all-rfmo-models/", pattern = "5x5_count_kwh.csv", full.names = T)

count_5x5_gfw <- NULL

for(file in list_files) {
  temp <- read.csv(file)
  count_5x5_gfw <- bind_rows(count_5x5_gfw, temp)
} 
  
# 5x5 data - mt and count
list_files<- list.files("../../data/model-data/inputs/all-rfmo-models/", pattern = "5x5_mt_to_count_hooks.csv", full.names = T)

mt_5x5_obs <- NULL 

for(file in list_files) {
  temp <- read.csv(file)
  mt_5x5_obs <- bind_rows(mt_5x5_obs, temp)
} 

list_files<- list.files("../../data/model-data/inputs/all-rfmo-models/", pattern = "5x5_mt_to_count_kwh.csv", full.names = T)

mt_5x5_gfw <- NULL

for(file in list_files) {
  temp <- read.csv(file)
  mt_5x5_gfw <- bind_rows(mt_5x5_gfw, temp)
} 

# 1x1 data - count only
list_files<- list.files("../../data/model-data/inputs/all-rfmo-models/", pattern = "1x1_count_hooks.csv", full.names = T)

count_1x1_obs <- NULL 

for(file in list_files) {
  temp <- read.csv(file)
  count_1x1_obs <- bind_rows(count_1x1_obs, temp)
} 

list_files<- list.files("../../data/model-data/inputs/all-rfmo-models/", pattern = "1x1_count_kwh.csv", full.names = T)

count_1x1_gfw <- NULL

for(file in list_files) {
  temp <- read.csv(file)
  count_1x1_gfw <- bind_rows(count_1x1_gfw, temp)
} 
  
# 1x1 data - mt and count
list_files<- list.files("../../data/model-data/inputs/all-rfmo-models/", pattern = "1x1_mt_to_count_hooks.csv", full.names = T)

mt_1x1_obs <- NULL 

for(file in list_files) {
  temp <- read.csv(file)
  mt_1x1_obs <- bind_rows(mt_1x1_obs, temp)
} 

list_files<- list.files("../../data/model-data/inputs/all-rfmo-models/", pattern = "1x1_mt_to_count_kwh.csv", full.names = T)

mt_1x1_gfw <- NULL

for(file in list_files) {
  temp <- read.csv(file)
  mt_1x1_gfw <- bind_rows(mt_1x1_gfw, temp)
} 
```

```{r eval=FALSE, include=FALSE}
# Run effort scenarios... 
# 5x5 data - count only
results_5x5_count <- all_rfmo_selector_models(data_gfw = count_5x5_gfw, data_effort = count_5x5_obs, save_loc = paste0(save_loc, "5x5_count_selector_"))
# results_5x5_count <- all_rfmo_effort_models(data_gfw = count_5x5_gfw, data_effort = count_5x5_obs, save_loc = paste0(save_loc, "5x5_count_"))

# 5x5 data - mt and count
results_5x5_mt <- all_rfmo_selector_models(data_gfw = mt_5x5_gfw, data_effort = mt_5x5_obs, save_loc = paste0(save_loc, "5x5_mt_to_count_selector_"))
# results_5x5_mt <- all_rfmo_effort_models(data_gfw = mt_5x5_gfw, data_effort = mt_5x5_obs, save_loc = paste0(save_loc, "5x5_mt_to_count_"))

# 1x1 data - count only
results_1x1_count <- all_rfmo_selector_models(data_gfw = count_1x1_gfw, data_effort = count_1x1_obs, save_loc = paste0(save_loc, "1x1_count_selector_"))
# results_1x1_count <- all_rfmo_effort_models(data_gfw = count_1x1_gfw, data_effort = count_1x1_obs, save_loc = paste0(save_loc, "1x1_count_"))

# 1x1 data - mt and count
results_1x1_mt <- all_rfmo_selector_models(data_gfw = mt_1x1_gfw, data_effort = mt_1x1_obs, save_loc = paste0(save_loc, "1x1_mt_to_count_selector_"))
# results_1x1_mt <- all_rfmo_effort_models(data_gfw = mt_1x1_gfw, data_effort = mt_1x1_obs, save_loc = paste0(save_loc, "1x1_mt_to_count_"))
```


```{r}
# Best performing models in terms of effort
# IATTC - regular model, 1x1 with count and mt, effort reported with target catch by flag
run_all_rfmo_models_others(data = mt_1x1_obs, rfmos = "IATTC", effort_source = "effort reported with target catch (flag)", 
                           save_loc = save_loc)
# ICCAT - regular model, 1x1 with count only, effort reported with target catch by flag
run_all_rfmo_models_others(data = count_1x1_obs, rfmos = "ICCAT", effort_source = "effort reported with target catch (flag)", 
                           save_loc = save_loc)
# IOTC - selector model, 5x5 with count only, effort reported with target catch by flag - will other regular models perform better?
run_all_rfmo_models_others(data = count_5x5_obs, rfmos = "IOTC", effort_source = "effort reported with target catch (flag)", 
                           save_loc = save_loc)
# WCPFC - regular model, 5x5 with count only, effort reported with bycatch
run_all_rfmo_models_others(data = count_5x5_obs, rfmos = "WCPFC", effort_source = "effort reported with bycatch (flag)", 
                           save_loc = save_loc)
```

```{r}
# Find best performing models
all_model_results <- read.csv(paste0(save_loc, "5x5_count_selector_all_rfmos_effort_results.csv")) %>% 
  mutate(type = "selector", 
         option = "5x5, count only") %>% 
  bind_rows(read.csv(paste0(save_loc, "5x5_mt_to_count_selector_all_rfmos_effort_results.csv")) %>% 
              mutate(type = "selector", 
                     option = "5x5, count and mt")) %>% 
  bind_rows(read.csv(paste0(save_loc, "1x1_count_selector_all_rfmos_effort_results.csv")) %>% 
              mutate(type = "selector", 
                     option = "1x1, count only")) %>% 
  bind_rows(read.csv(paste0(save_loc, "1x1_mt_to_count_selector_all_rfmos_effort_results.csv")) %>% 
              mutate(type = "selector", 
                     option = "1x1, count and mt")) %>% 
  bind_rows(read.csv(paste0(save_loc, "5x5_count_all_rfmos_effort_results.csv")) %>%
              mutate(type = "regular", 
                     option = "5x5, count only")) %>% 
  bind_rows(read.csv(paste0(save_loc, "5x5_mt_to_count_all_rfmos_effort_results.csv")) %>%
              mutate(type = "regular", 
                     option = "5x5, count and mt")) %>%
  bind_rows(read.csv(paste0(save_loc, "1x1_count_all_rfmos_effort_results.csv")) %>%
              mutate(type = "regular", 
                     option = "1x1, count only")) %>% 
  bind_rows(read.csv(paste0(save_loc, "1x1_mt_to_count_all_rfmos_effort_results.csv")) %>%
              mutate(type = "regular", 
                     option = "1x1, count and mt")) %>% 
  bind_rows(read.csv(paste0(save_loc, "IATTC_models_others_results.csv")) %>%
              mutate(type = "exhaustive search", 
                     rfmo = "IATTC",
                     option = "1x1, count and mt") %>% 
              rowwise() %>% 
              mutate(specifics = paste0("environmentals = ", environmental_value, ", include ssh = ", 
                                        include_ssh, ", price = ", price, ", catch transformation = ", catch_transformation), 
                     option = paste0(option, ";", specifics))) %>% 
  bind_rows(read.csv(paste0(save_loc, "ICCAT_models_others_results.csv")) %>%
              mutate(type = "exhaustive search", 
                     rfmo = "ICCAT",
                     option = "1x1, count") %>% 
              rowwise() %>% 
              mutate(specifics = paste0("environmentals = ", environmental_value, ", include ssh = ", 
                                        include_ssh, ", price = ", price, ", catch transformation = ", catch_transformation), 
                     option = paste0(option, ";", specifics))) %>% 
  bind_rows(read.csv(paste0(save_loc, "IOTC_models_others_results.csv")) %>%
              mutate(type = "exhaustive search", 
                     rfmo = "IOTC",
                     option = "5x5, count") %>% 
              rowwise() %>% 
              mutate(specifics = paste0("environmentals = ", environmental_value, ", include ssh = ", 
                                        include_ssh, ", price = ", price, ", catch transformation = ", catch_transformation), 
                     option = paste0(option, ";", specifics))) %>% 
  bind_rows(read.csv(paste0(save_loc, "WCPFC_models_others_results.csv")) %>%
              mutate(type = "exhaustive search", 
                     rfmo = "WCPFC",
                     option = "5x5, count") %>% 
              rowwise() %>% 
              mutate(specifics = paste0("environmentals = ", environmental_value, ", include ssh = ", 
                                        include_ssh, ", price = ", price, ", catch transformation = ", catch_transformation), 
                     option = paste0(option, ";", specifics)))

all_model_results %>%
  select(rfmo, type, option, effort_source, rsq) %>%
  group_by(rfmo) %>% 
  slice_max(., rsq)
```



```{r}
# Run the best performing model and return a full prediction for that RFMO
# IOTC
all_rfmo_models(data = count_5x5_obs, rfmos = "IOTC", effort_source = "effort reported with bycatch (flag)", save_loc = save_loc)

# ICCAT
all_rfmo_models(data = count_1x1_obs, rfmos = "ICCAT", effort_source = "effort reported with target catch (flag)", save_loc = save_loc)

# IATTC
all_rfmo_models(data = mt_1x1_obs, rfmos = "IATTC", effort_source = "effort reported with target catch (flag)", save_loc = save_loc)

# WCPFC
all_rfmo_models(data = count_5x5_obs, rfmos = "WCPFC", effort_source = "effort reported with bycatch (flag)", save_loc = save_loc)
```

