---
title: "Data Cleaning for ML - WCPFC Data Only"
output: html_notebook
---

This notebook combines RFMO catch data with SDM, SST, SSH, chl-a, and GFW data for WCPFC using the default 5x5 degree grid system and an annual reporting scale. 


```{r message=FALSE, warning=FALSE, include=FALSE}
# Load Libraries
library(tidyverse)
library(readxl)
library(googledrive)
library(sf)
library(rgdal)
```

```{r include=FALSE}
# Load Data - only keeping wcpfc for now
dat <- vroom::vroom("../../data/rfmo-observer-data/outputs/all_data.csv") %>% 
  filter(rfmo == "WCPFC") 

# Species grouping
species_groups <- read_xlsx("../../data/species-information/species_groups.xlsx", sheet = "species_list")

# SDM data
sdms <- read.csv("../../data/iucn-sdm-data/outputs/global_combined_iucn_sdm_5x5.csv") %>% 
  distinct_all()
sdms_1x1 <- read.csv("../../data/iucn-sdm-data/outputs/global_combined_iucn_sdm_1x1.csv") %>% 
  distinct_all()

# SST data
sst_wcpfc <- read.csv("../../data/sea-surface-temperature/outputs/binned_global_sst_5x5.csv") %>% 
  distinct_all()
sst_wcpfc_1x1 <- read.csv("../../data/sea-surface-temperature/outputs/binned_global_sst_1x1.csv") %>% 
  distinct_all()

# Chlorophyll-A data
chla_wcpfc <- read.csv("../../data/chlorophyll-a/outputs/binned_global_chla_5x5.csv") %>% 
  distinct_all()
chla_wcpfc_1x1 <- read.csv("../../data/chlorophyll-a/outputs/binned_global_chla_1x1.csv") %>% 
  distinct_all()

# Sea surface height
ssh_wcpfc <- read.csv("../../data/sea-surface-height/outputs/binned_global_ssh_5x5.csv") %>% 
  distinct_all()
ssh_wcpfc_1x1 <- read.csv("../../data/sea-surface-height/outputs/binned_global_ssh_1x1.csv") %>% 
  distinct_all()

# Ex-vessel price data
prices <- read.csv("../../data/ex-vessel-prices/exvessel_price_database_1976_2017.csv") %>% 
  distinct_all()

prices <- prices %>% 
  mutate(ASFIS_species = str_to_upper(ASFIS_species), 
         scientific_name = str_to_upper(scientific_name), 
         ASFIS_species = case_when(ASFIS_species == "INDO-PACIF. BOTTLENOSE DOLPHIN" ~  "INDO-PACIFIC BOTTLENOSE DOLPHIN", 
                                   ASFIS_species == "SHORTFIN MAKO" ~ "SHORTFIN MAKO SHARK", 
                                   ASFIS_species == "ALBACORE" ~ "ALBACORE TUNA", 
                                   TRUE ~ ASFIS_species), 
         ISSCAAP_group = case_when(ISSCAAP_group == "Sharks, rays, chimaeras" ~ "sharks and rays", 
                                   ISSCAAP_group == "Miscellaneous aquatic mammals" ~ "marine mammals", 
                                   ISSCAAP_group == "Turtles" ~ "turtles", 
                                   TRUE ~ paste(ISSCAAP_group))) %>% 
  rename(year = Year, 
         species_commonname = ASFIS_species, 
         species_group = ISSCAAP_group)

# GFW data
gfw_wcpfc <- read.csv("../../data/global-fishing-watch/outputs/binned_global_gfw_5x5.csv")
gfw_wcpfc_1x1 <- read.csv("../../data/global-fishing-watch/outputs/binned_global_gfw_1x1.csv")

# Save path
save_path = "../../data/model-data/inputs/wcpfc-only-model/"
```

```{r message=FALSE, warning=FALSE}
# Add species group names
dat <- dat %>% 
  left_join(species_groups %>% 
              filter(!is.na(scientific_name)) %>%
              mutate(scientific_name = toupper(scientific_name)) %>% 
              dplyr::select(scientific_name, group), by = c("species_sciname" = "scientific_name")) %>% 
  # Fixing additional species issues
  mutate(species_sciname = case_when(species_sciname == "MESOPLODONGINKGODENS" ~
                                     "MESOPLODON GINKGODENS",
                                     species_commonname == "SHARKS NEI" ~ "SHARKS NEI", 
                                     TRUE ~ paste(species_sciname)), 
         species_commonname = case_when(species_commonname == "OTHER SHARKS" ~ "SHARKS NEI",
                                        species_commonname == "OTHER TUNA" ~ "TUNAS NEI",
                                        TRUE ~ species_commonname),
         species_sciname = case_when(species_commonname == "TUNAS NEI" ~ "THUNNUS",
                                     is.na(species_sciname) ~ species_commonname,
                                     TRUE ~ gsub(" SPP|[.]", "", species_sciname)),  
         group = case_when(species_commonname == "SHARKS NEI" ~ "sharks and rays", 
                           species_commonname %in% c("DWARF SPERM WHALE", "AQUATIC MAMMALS NEI", 
                                                     "SPOTTED DOLPHINS NEI", "WHALES NEI", 
                                                     "GINKGO-TOOTHED BEAKED WHALE") ~ "marine mammals", 
                           species_commonname %in% c("ALBATROSSES NEI", "BIRDS NEI", "GULLS - TERNS AND SKUAS", 
                                                     "WANDERING ALBATROSS COMPLEX", "SHY ALBATROSS NEI", 
                                                     "WEDGE-TAILED SHEARWATER", "COMMON DIVING PETREL", 
                                                     "STORM PETRELS", "PRIONS NEI", "GREY-BACK STORM PETREL", 
                                                     "ROYAL ALBATROSSES") ~ "seabirds", 
                           TRUE ~ paste(group))) %>% 
  dplyr::rename(species_group = group) %>% 
  filter(effort_units %in% c("sets", "hooks") & time_period == "yearly") %>% 
  distinct_all() %>% # duplicated turtles because of multiple "turtles nei" in the species list
  filter(species_group %in% c("tunas", "tuna-like species", "sharks and rays")) %>% # only really care about these for now
  filter(year >= 2012)

update_species_groups <- dat %>% 
  select(species_sciname, species_commonname, species_group) %>% 
  distinct_all()

# Split into target vs bycatch
target <- dat %>% 
  filter(species_group %in% c("tunas", "tuna-like species")) %>% 
  mutate(catch_units = gsub("metric ", "", catch_units), 
         country = ifelse(is.na(country), "NA Country", paste(country)), 
         settype = ifelse(is.na(settype), "longline", paste(settype)), 
         settype = gsub("other", "purseseine other", paste(settype))) %>% 
  dplyr::select(year, time_period, country, latitude, longitude, gear, settype, effort, 
         effort_units, species_commonname, catch, catch_units, sources, species_group, observer_coverage)  %>% 
  distinct_all() %>% 
  group_by(year, time_period, country, latitude, longitude, gear, settype, 
         effort_units, species_commonname, catch_units, sources, species_group, observer_coverage) %>% 
  summarise(catch = sum(catch, na.rm = T), 
            effort = sum(effort, na.rm = T)) %>% 
  ungroup()

###
# median prices by species group
###
target_prices <- prices %>% 
  filter(species_commonname %in% unique(target$species_commonname)) %>% 
  left_join(species_groups %>% dplyr::select(scientific_name, group) %>% mutate(scientific_name = str_to_upper(scientific_name)), 
            by = c("scientific_name")) %>%
  group_by(year, group) %>% 
  summarise(median_target_price = median(exvessel, na.rm = T)) %>% 
  ungroup() %>% 
  filter(year >= 2012)

# adjust for 2018
target_prices <- target_prices %>% 
  bind_rows(target_prices %>% 
              filter(year == 2017) %>% 
              mutate(year = 2018, 
                     median_target_price = median_target_price * 1.02442477))

# pivot wider
target_prices  <- target_prices %>%
  pivot_wider(values_from = median_target_price, names_from = group) %>% 
  rename(median_tuna_price = tunas,
         median_tunalike_price = `tuna-like species`) 

###
# target prices for individuals
###
target_prices_ind <- prices %>% 
  filter(species_commonname %in% unique(target$species_commonname)) %>% 
  left_join(species_groups %>% dplyr::select(scientific_name, group) %>% mutate(scientific_name = str_to_upper(scientific_name)), 
            by = c("scientific_name")) %>%
  group_by(year, scientific_name) %>% 
  summarise(spp_target_price = median(exvessel, na.rm = T)) %>% 
  ungroup() %>% 
  filter(year >= 2012)

# Adjust for 2018
target_prices_ind <- target_prices_ind %>% 
  bind_rows(target_prices_ind %>% 
              filter(year == 2017) %>% 
              mutate(year = 2018, 
                     spp_target_price = spp_target_price * 1.02442477))
  
  
# Create pivoted table for target catch by species*catch unit*set type*country etc
target_catch_pivot <- target %>% 
  select(-country, -settype, -effort, - effort_units, - species_commonname, - species_group) %>% 
  pivot_wider(names_from = c(catch_units),
                          values_from = c(catch),
                          values_fn = sum, 
                          values_fill = 0) %>% 
  full_join( target %>% 
               select(-country, -settype, -effort, - effort_units, - species_commonname) %>% 
               pivot_wider(names_from = c(catch_units, species_group),
                          values_from = c(catch),
                          values_fn = sum, 
                          values_fill = 0) %>% 
               rename(count_tunalike = `count_tuna-like species`, 
                      tonnes_tunalike = `tonnes_tuna-like species`), 
             by = c("year", "gear", "time_period", "longitude", "latitude", "sources", "observer_coverage")) %>% 
  full_join(target %>% 
              select(-effort, - effort_units, - species_commonname, - species_group) %>% 
              pivot_wider(names_from = c(catch_units, country, settype), 
                          values_from = c(catch), 
                          values_fn = sum, 
                          values_fill = 0), 
            by = c("year", "gear", "time_period", "longitude", "latitude", "sources", "observer_coverage")) %>%
   full_join(target %>% 
              select(-effort, -effort_units,  - species_group) %>% 
              pivot_wider(names_from = c(species_commonname, catch_units, country, settype), 
                          values_from = c(catch), 
                          values_fn = sum, 
                          values_fill = 0), 
            by = c("year", "gear", "time_period", "longitude", "latitude", "sources", "observer_coverage")) 

# Fix colnames to reflect that this is for targeted catch
colnames(target_catch_pivot)[8:ncol(target_catch_pivot)] <- paste0("target_catch_", colnames(target_catch_pivot)[8:ncol(target_catch_pivot)])

# Grab effort data reported with target species (only keep distinct rows - duplicates need to be removed from where multiple species are reported from the same group)
target_effort_pivot <- target %>% 
  select(year, time_period, latitude, longitude, country, gear, settype, effort, effort_units, sources, observer_coverage) %>% 
  distinct_all()

# Create target effort pivot table for all and by country and by set type
target_effort_pivot <- target_effort_pivot %>% 
  group_by(year, time_period, latitude, longitude, gear, effort_units, sources, observer_coverage) %>% 
  summarise(target_effort = sum(effort)) %>% 
  ungroup() %>% 
  full_join(target_effort_pivot %>%
               pivot_wider(names_from = c(country, settype), 
                           values_from = c(effort), 
                           values_fn = sum, 
                           values_fill = 0), 
            by = c("year", "time_period", "latitude", "longitude", "gear", "effort_units", "sources", "observer_coverage"))

# Fix colnames to reflect that this is for targeted effort
colnames(target_effort_pivot)[10:ncol(target_effort_pivot)] <- paste0("target_effort_", colnames(target_effort_pivot)[10:ncol(target_effort_pivot)])

# Bring back together
all_target <- target_effort_pivot %>% 
  full_join(target_catch_pivot, 
            by = c("year", "time_period", "latitude", "longitude", "gear", "sources", "observer_coverage")) %>% 
  left_join(target_prices, by = "year") %>% 
  mutate_at(vars(target_effort:`target_catch_YELLOWFIN TUNA_tonnes_Kiribati_purseseine other`), round)

# Repeat (sort of) for bycatch data
all_bycatch <- dat %>% 
  filter(!(species_group %in% c("tunas", "tuna-like species"))) %>% 
  select(year, gear, longitude, latitude, effort, effort_units, species_commonname, 
         species_sciname, catch, catch_units, spatial_notes, species_group, sources, observer_coverage) %>% 
  filter(species_commonname != "OTHER SPECIES") %>% 
  distinct_all() %>% 
  group_by(year, gear, longitude, latitude, effort_units, species_commonname, 
         species_sciname, catch_units, spatial_notes, species_group, sources, observer_coverage) %>% 
  summarise(catch = sum(catch, na.rm = T), 
            effort = sum(effort, na.rm = T)) %>% 
  ungroup() %>% 
  mutate_at(vars(catch:effort), round)

remove(dat, target_catch_pivot, target_effort_pivot, target)

# Merge all data back together

# First save list of species groups and scinames
species_groups_short <- all_bycatch %>% 
              select(species_sciname, species_commonname, species_group) %>% 
              distinct_all()

all_dat <- all_bycatch %>% 
  full_join(all_target %>% rename(target_sources = sources, target_observer_coverage = observer_coverage), 
            by = c("year", "latitude", "longitude", "gear", "effort_units")) %>% 
  rename(target_aggregation_period = time_period) %>%
  mutate(species_sciname = ifelse(is.na(species_sciname), "empty", species_sciname))
  

remove(all_bycatch, all_target)

bycatch_spp <- all_dat %>% 
  select(species_sciname, catch_units) %>% 
  distinct_all() %>% 
  mutate(name = paste(species_sciname, catch_units, sep = "_"))

# Pad with zeros
all_dat <- all_dat %>% 
  select(-species_commonname, - species_group) %>% 
  pivot_wider(names_from = species_sciname,
              values_from = catch, 
              values_fill = 0) %>% 
  pivot_longer(cols = bycatch_spp$species_sciname, 
               names_to = c("species_sciname"),
               values_to = "catch") %>% 
  relocate(species_sciname, .after = latitude) %>% 
  relocate(catch, .after = species_sciname) %>% 
  relocate(year, .before = gear) %>% 
  filter(species_sciname != "empty") %>% 
  mutate(catch_units = "count", 
         spatial_notes = "center of 5x5 cell", 
         sources = "bycatch and effort from observers") %>% 
  left_join(., update_species_groups) # add back in
```

```{r rescale-rfmo-data}
# Rescale to 1x1 degree - for later
locations_y <- all_dat %>%
  select(latitude) %>%
  distinct_all() %>%
  mutate(latitude_lag0 = latitude,
         latitude_lag1 = latitude-1,
         latitude_lag2 = latitude-2,
         latitude_plus1 = latitude+1,
         latitude_plus2 = latitude+2) %>%
  pivot_longer(latitude_lag0:latitude_plus2, values_to = "latitude_rescaled") %>%
  select(-name)

locations_x <- all_dat %>%
  select(longitude) %>%
  distinct_all() %>%
  mutate(longitude_lag0 = longitude,
         longitude_lag1 = longitude-1,
         longitude_lag2 = longitude-2,
         longitude_plus1 = longitude+1,
         longitude_plus2 = longitude+2) %>%
  pivot_longer(longitude_lag0:longitude_plus2, values_to = "longitude_rescaled") %>%
  select(-name)

# New dataset
all_dat_1x1 <- all_dat %>%
  left_join(locations_y) %>%
  left_join(locations_x) %>%
  mutate(longitude_rescaled = ifelse(is.na(longitude_rescaled), longitude, longitude_rescaled),
         latitude_rescaled = ifelse(is.na(latitude_rescaled), latitude, latitude_rescaled),
         catch = catch/25) %>%
  mutate_at(vars(effort, target_effort:`target_catch_YELLOWFIN TUNA_tonnes_Kiribati_purseseine other`), function(x){ x/25}) %>% # rescale all to be at 1x1
  rename(latitude_orig = latitude,
         longitude_orig = longitude,
         latitude = latitude_rescaled,
         longitude = longitude_rescaled) %>%
  mutate(spatial_notes = "center of 1x1 cell") %>%
  select(colnames(all_dat)) 

all_dat_1x1_comb <- all_dat_1x1 %>% 
  filter(effort_units == "hooks") %>% 
  mutate(year = as.integer(year)) %>% 
  filter(spatial_notes == "center of 1x1 cell" & catch_units == "count") %>% 
  filter(year >= 2012 & year <= 2018) %>% # lower limit for GFW data
  left_join(sdms_1x1 %>% distinct_all()) %>% 
  left_join(sst_wcpfc_1x1 %>% distinct_all()) %>% 
  left_join(chla_wcpfc_1x1 %>% distinct_all()) %>% 
  filter(!is.na(mean_chla) | !is.na(mean_sst)) %>%
  filter(!is.na(sdm)) %>% 
  mutate(rfmo = "WCPFC") %>% 
  rename(gear_group = gear) %>% 
  select(rfmo, year, latitude, longitude, species_sciname, catch, catch_units, gear_group, colnames(.)[grepl("target_effort", colnames(.)) & grepl("longline", colnames(.))], species_commonname, species_group, sdm, mean_sst, median_sst, min_sst, max_sst, se_sst, cv_sst, 
         mean_chla, median_chla, min_chla, max_chla, sd_chla, se_chla, cv_chla)

write.csv(all_dat_1x1_comb, paste0(save_path, "wcpfc_1x1_hooks.csv"), row.names = F)

all_dat_1x1_comb <- all_dat_1x1 %>% 
  filter(effort_units == "hooks") %>%
  rename(gear_group = gear) %>% 
  mutate(year = as.integer(year)) %>% 
  filter(spatial_notes == "center of 1x1 cell" & catch_units == "count") %>% 
  filter(year >= 2012 & year <= 2018) %>% # lower limit for GFW data 
  left_join(gfw_data_1x1 %>% distinct_all()) %>% 
  left_join(sdms_1x1 %>% distinct_all()) %>% 
  left_join(sst_wcpfc_1x1 %>% distinct_all()) %>% 
  left_join(chla_wcpfc_1x1 %>% distinct_all()) %>% 
  filter(!is.na(mean_chla) | !is.na(mean_sst)) %>%
  filter(!is.na(sdm)) %>% 
  mutate(rfmo = "WCPFC") %>% 
  select(rfmo, year, latitude, longitude, species_sciname, catch, catch_units, gear_group, total_fishing_kwh, species_commonname, species_group, sdm, mean_sst, median_sst, min_sst, max_sst, se_sst, cv_sst, 
         mean_chla, median_chla, min_chla, max_chla, sd_chla, se_chla, cv_chla)

write.csv(all_dat_1x1_comb, paste0(save_path, "wcpfc_1x1_kwh.csv"), row.names = F)
```



```{r message=FALSE, warning=FALSE}
# Join with sdm data 
dat_sdm <- all_dat %>% 
  select(latitude, longitude, species_commonname) %>% 
  distinct_all() %>% 
  left_join(species_groups_short) %>% 
  filter(!is.na(species_sciname)) %>%
  left_join(., sdms, by = c("latitude", "longitude", 
                               "species_sciname")) %>% 
  rename(sdm_probability = sdm)

grouped_sdm <- dat_sdm %>% 
  group_by(species_group, latitude, longitude) %>% 
  summarise(sdm = sum(sdm_probability, na.rm = T)) %>% 
  ungroup() %>% 
  group_by(species_group) %>% 
  mutate(total_sdm = sum(sdm, na.rm = T)) %>%
  ungroup() %>% 
  mutate(sdm_scaled = sdm/total_sdm) %>% 
  select(-sdm, -total_sdm) %>% 
  pivot_wider(values_from = sdm_scaled, names_from = species_group) %>% 
  rename(sharks_sdm = `sharks and rays`)

remove(species_groups, species_groups_short, scaled_sdm)
```


```{r message=FALSE, warning=FALSE}
# Add SST data
# Merge with wcpfc data
dat_sst <- all_dat %>% 
  select(year, latitude, longitude) %>% 
  distinct_all() %>%
  left_join(sst_wcpfc, by = c("longitude", "latitude", "year"))

remove(sst_wcpfc)
```

```{r message=FALSE, warning=FALSE}
# Add CHLA data
# Merge with wcpfc data
dat_chla <- all_dat %>% 
  select(year, latitude, longitude) %>% 
  distinct_all() %>%
  left_join(chla_wcpfc, by = c("longitude", "latitude", "year"))

remove(chla_wcpfc)
```

```{r message=FALSE, warning=FALSE}
# Add SSH data
# Merge with wcpfc data
dat_ssh <- all_dat %>% 
  select(year, latitude, longitude) %>% 
  distinct_all() %>%
  left_join(ssh_wcpfc, by = c("longitude", "latitude", "year"))

remove(chla_wcpfc)
```

```{r}
# Merge everything together... 
environmentals <- dat_sst %>% 
  full_join(dat_chla) %>% 
  full_join(dat_ssh) %>% 
  arrange(year, latitude, longitude) %>% 
  fill(mean_sst:cv_ssh)

remove(dat_sst, dat_chla)

all_dat <- all_dat %>% 
  left_join(environmentals) %>% 
  left_join(dat_sdm) %>% 
  relocate("species_sciname":"species_group", .after = species_commonname) %>% 
  relocate(sdm_probability, .after = spatial_notes) %>% 
  relocate("mean_sst":"cv_ssh", .after = sdm_probability)

###
# median prices by species group
###
spp_prices <- prices %>% 
  mutate(scientific_name = gsub(" SPP", "", scientific_name)) %>%
  filter(scientific_name %in% unique(all_dat$species_sciname)) %>% 
  group_by(year) %>% 
  summarise(median_price_group = median(exvessel, na.rm = T)) %>% 
  ungroup() %>% 
  filter(year >= 2012) 

# adjust for 2018
spp_prices <- spp_prices %>% 
  bind_rows(spp_prices %>% 
              filter(year == 2017) %>% 
              mutate(year = 2018, 
                     median_price_group = median_price_group * 1.02442477))

###
# target prices for individuals
###
spp_prices_ind <- prices %>% 
  mutate(scientific_name = gsub(" SPP", "", scientific_name)) %>% 
  bind_rows(prices %>% filter(grepl("SPHYRNA", scientific_name)) %>% 
              group_by(year) %>% 
              summarise(exvessel = median(exvessel, na.rm = T)) %>% 
              ungroup() %>% 
              mutate(scientific_name = "SPHYRNA")) %>% 
  filter(scientific_name %in% unique(all_dat$species_sciname)) %>% 
  group_by(year, scientific_name) %>% 
  summarise(median_price_species = median(exvessel, na.rm = T)) %>% 
  ungroup() %>% 
  filter(year >= 2012) 

# Adjust for 2018
spp_prices_ind <- spp_prices_ind  %>% 
  bind_rows(spp_prices_ind %>% 
              filter(year == 2017) %>% 
              mutate(year = 2018, 
                     median_price_species = median_price_species * 1.02442477))

# Add species that aren't there
spp_prices_ind <- spp_prices_ind  %>% 
  bind_rows(spp_prices %>% 
              mutate(scientific_name = "SHARKS NEI") %>% 
              rename(median_price_species = median_price_group) %>% 
              select(year, scientific_name, median_price_species)) %>% 
    bind_rows(spp_prices %>% 
              mutate(scientific_name = "RHINCODON TYPUS") %>% # don't have any data for whaleshark so we will just use all
              rename(median_price_species = median_price_group) %>% 
              select(year, scientific_name, median_price_species))

# combine data
all_dat <- all_dat %>% 
  left_join(spp_prices, by = c("year")) %>% 
  left_join(spp_prices_ind, by = c("year", "species_sciname" = "scientific_name"))

# # add scaled sdms for future models
# all_dat <- all_dat %>% 
#   left_join(grouped_sdm, by = c("latitude", "longitude"))

# Save data before adding GFW
# Monthly self-reported
write.csv(all_dat %>% 
            filter(target_sources == "self-reported catch and effort by month") %>% 
            select(year:target_effort, target_catch_count, target_catch_count_tunas, target_catch_count_tunalike,
                   target_catch_tonnes, target_catch_tonnes_tunas, target_catch_tonnes_tunalike,  
                   median_price_species, median_price_group, median_tuna_price, median_tunalike_price,
                   # marine_mammal_sdm, sharks_sdm, tunalike_sdm, tunas_sdm, turtles_sdm, 
                   colnames(all_dat)[grepl("NA Country", colnames(all_dat))]), paste0(save_path, "wcpfc_monthly.csv"), 
          row.names = FALSE)

# Flag + quarter self reported
write.csv(all_dat %>% 
            filter(target_sources == "self-reported catch and effort by flag + quarter"), paste0(save_path, "wcpfc_flagquarter.csv"), 
          row.names = FALSE)

# Flag + year self reported
write.csv(all_dat %>% 
            filter(target_sources == "self-reported catch and effort by flag + year"),  paste0(save_path, "wcpfc_flagyear.csv"), 
          row.names = FALSE)
```

```{r}
# GFW data
# Merge with wcpfc data
all_dat <- all_dat %>% 
  left_join(gfw_wcpfc %>% filter(rfmo == "WCPFC") %>% select(-rfmo), 
            by = c("longitude", "latitude", "year", "gear" = "gear_group"))
```


```{r}
# Save data
write.csv(all_dat, paste0(save_path,"wcpfc_all.csv"), row.names = FALSE)

# GFW only
write.csv(all_dat %>% 
            select(year:observer_coverage, target_catch_count, target_catch_count_tunas, target_catch_count_tunalike,
                   target_catch_tonnes, target_catch_tonnes_tunas, target_catch_tonnes_tunalike, 
                   median_price_species, median_price_group, median_tuna_price, median_tunalike_price, 
                   # marine_mammal_sdm, sharks_sdm, tunalike_sdm, tunas_sdm, turtles_sdm, 
                   total_fishing_kwh) %>% distinct_all(), paste0(save_path, "wcpfc_gfw.csv"), row.names = FALSE)

# Monthly self-reported
write.csv(all_dat %>% 
            filter(target_sources == "self-reported catch and effort by month") %>% 
            select(year:target_effort, target_catch_count, target_catch_count_tunas, target_catch_count_tunalike,
                   target_catch_tonnes, target_catch_tonnes_tunas, target_catch_tonnes_tunalike, 
                   median_price_species, median_price_group, median_tuna_price, median_tunalike_price,
                   # marine_mammal_sdm, sharks_sdm, tunalike_sdm, tunas_sdm, turtles_sdm, 
                   colnames(all_dat)[grepl("NA Country", colnames(all_dat))], total_fishing_kwh) %>%
            distinct_all(), paste0(save_path, "wcpfc_monthly_with_gfw.csv"), 
          row.names = FALSE)

# Flag + quarter self reported
write.csv(all_dat %>% 
            filter(target_sources == "self-reported catch and effort by flag + quarter") %>% distinct_all(),
          paste0(save_path, "wcpfc_flagquarter_with_gfw.csv"), 
          row.names = FALSE)

# Flag + year self reported
write.csv(all_dat %>% 
            filter(target_sources == "self-reported catch and effort by flag + year") %>% distinct_all(),
          paste0(save_path, "wcpfc_flagyear_with_gfw.csv"), 
          row.names = FALSE)
```

